import Head from "next/head";
import Body from "./components/Body";
import Footer from "./components/Footer";
import Header from "./components/Header";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Dinesh's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <div className="home">
        <div>
          <Header />
        </div>
        <div>
          <Body />
        </div>
        <div>
          <Footer />
        </div>
      </div>
    </div>
  );
}
